### ISSUE TITLE
give hover effect for navbar elements

### ISSUE THREAD

**Issue by mannar-1** [EventsAtForce/eventsatforce-website#19]
![image](https://github.com/user-attachments/assets/eb77d5b7-4330-472d-808a-c255b2e768a1)
i want to add hover effect to navbar elements 
rest all component in the site have hover effect except the navbar so can you please assign this to me 
under hacktoberfest label

**Comment by JayZ6969** [comment]
Sure ! Fork the repo, make all the changes needed only in the *dev-main* branch and create a pull request. Will be accepted after reviewing your commits. Happy Hacking :)

**Comment by AkshatGupta2005** [comment]
Please assign this issue to me

**Comment by Shubham0523** [comment]
I would love to work on this issue and would like to implement a hover effect like this: 

![Raed India - Brave 19-10-2024 14_37_29](https://github.com/user-attachments/assets/68544a73-8dc8-4f6d-ac82-dc142d6febcc)

**Comment by Shubham0523** [comment]
thank you @JayZ6969 . please assign hacktober fest also to this label

**Comment by JayZ6969** [comment]
Yeah, create the PR first, We'll label that PR if we accept it.

**Comment by Shubham0523** [comment]
I have added the PR @JayZ6969 please review
