### ISSUE TITLE
Scroll to Top Button 

### ISSUE THREAD

**Issue by JayZ6969** [EventsAtForce/eventsatforce-website#21]
Scroll to Top Button needed for both Desktop and Mobile devices.

**Comment by Shubham0523** [comment]
I would love to work on this! @JayZ6969

**Comment by syamjir** [comment]
@JayZ6969 , Assign me

**Comment by Shubham0523** [comment]
here is the design I have made and implemented on the website just waiting for the issue to be assigned to me so that I can create a PR 

![FORCE - REVA University - Brave 20-10-2024 00_21_01](https://github.com/user-attachments/assets/3258489d-808e-41d7-a142-a6a04fc92b8f)

**Comment by syamjir** [comment]
![Screenshot 2024-10-20 at 8 23 16 AM](https://github.com/user-attachments/assets/258ad2df-62b5-47f7-b098-47c5ddb216e4)
Hi@JayZ6969, I have created an icon that I believe suits your site and fits perfectly with your theme. If you're satisfied with the icon, please review the PR and  accept my pull request. If you need any improvements, feel free to ask—I'm ready to make any necessary changes.

**Comment by JayZ6969** [comment]
@syamjir Hey ! I really appreciate your contribution but, the scroll to top button is usually a hovering button. You can refer the 'Work with me' button in this project https://jayz6969.github.io/photography-portfolio/ .

**Comment by syamjir** [comment]
@JayZ6969 , I will adjust the code and then submit a PR
